#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/gpfs/bbp.cscs.ch/home/tharayil/generalized-neurodamus-py/neurodamus-py/.tox/py3/lib/python3.9/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/gpfs/bbp.cscs.ch/home/tharayil/generalized-neurodamus-py/neurodamus-py/.tox/py3/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/gpfs/bbp.cscs.ch/home/tharayil/generalized-neurodamus-py/neurodamus-py/x86_64/.libs/libnrnmech.so" "$@"
