name: Build Documentation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and neurodamus
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_docs.txt
          pip install -e .

      - name: Build documentation
        run: sphinx-build -T -W docs docs/_build
