name: Lint Check

on: [pull_request, push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install flake8
      run: pip install flake8-pyproject

    - name: Run flake8
      run: flake8 neurodamus tests
