name: Neurodamus Wheels

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish-wheel:
    steps:
      - name: Upload Wheel
        uses: BlueBrainProject/neurodamus/.github/workflows/build_test_wheels@v1
        needs: build-wheel
        env:
            PYPI_URL: ${{ secrets.PYPI_URL }}
            PYPI_USER: ${{ secrets.PYPI_USER }}
            PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip3 install twine
          python${{ matrix.python_version }} -m twine upload --username $PYPI_USER --password $PYPI_TOKEN dist/*
